apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: longhorn-idrive
  namespace: longhorn-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: longhorn-idrive
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: /platform/idrive-credentials/ACCESS_KEY_ID
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: /platform/idrive-credentials/ACCESS_SECRET_KEY
    - secretKey: AWS_ENDPOINTS
      remoteRef:
        key: /platform/idrive-credentials/E2_ENDPOINT
    - secretKey: AWS_REGION
      remoteRef:
        key: /platform/idrive-credentials/AWS_REGION
