apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
patches:
  - target:
      group: postgresql.cnpg.io
      version: v1
      kind: Cluster
      name: home-assistant-postgresql
    patch: |
      - op: replace
        path: /spec/bootstrap
        value:
          recovery:
            source: home-assistant-postgresql-backup
            database: home_assistant
            owner: home_assistant
