apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: github-actions-cache-server
  namespace: flux-system
spec:
  interval: 30m
  releaseName: github-actions-cache-server
  targetNamespace: github-actions-cache
  chartRef:
    kind: OCIRepository
    name: github-actions-cache-server
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: Deployment
              name: github-actions-cache-server
            patch: |
              - op: add
                path: /spec/strategy
                value:
                  type: Recreate
  values:
    image:
      repository: ghcr.io/falcondev-oss/github-actions-cache-server
      tag: 9.7.0@sha256:3999b0202ec509f3b2084ef92cc50b408838e0d442b5997dd6dff2d89f4fe7b4
    config:
      db:
        driver: postgres
    persistentVolumeClaim:
      enabled: true
      storageClassName: longhorn
    resources:
      limits:
        memory: 1Gi
      requests:
        cpu: 25m
        memory: 256Mi
    extraEnv:
      - name: DB_POSTGRES_URL
        valueFrom:
          secretKeyRef:
            name: github-actions-cache-postgresql-app
            key: uri
