---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: loki-cert
  namespace: loki
spec:
  secretName: loki-tls
  dnsNames:
    - loki.kakatkarakshay.dev
  issuerRef:
    name: cloudflare-clusterissuer
    kind: ClusterIssuer
