---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: loki
resources:
  - namespace.yaml
  - repo.yaml
  - release.yaml
  - certificate.yaml
  - ingress.yaml
  - middleware.yaml
  - promtail.yaml
configMapGenerator:
  - name: loki-values
    files:
      - values.yaml
  - name: promtail-values
    files:
      - values.yaml=promtail-values.yaml
configurations:
  - kustomizeconfig.yaml
