apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: codex-lb
  namespace: flux-system
spec:
  interval: 30m
  url: oci://ghcr.io/soju06/charts/codex-lb
  ref:
    tag: 1.25.0-beta.7
    digest: sha256:2f8c0535af621234f88c23af936f719f853a1a608daa2d25f5c6aac762ebd91e
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
