apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: codex-lb
  namespace: flux-system
spec:
  interval: 30m
  url: oci://ghcr.io/soju06/charts/codex-lb
  ref:
    tag: 1.25.0-beta.6
    digest: sha256:3667ff068601fe65383b8bb2e6874411dcfab03f1b31be998daaa4e7a1c97d86
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
