apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: codex-lb
  namespace: flux-system
spec:
  interval: 30m
  url: oci://ghcr.io/soju06/charts/codex-lb
  secretRef:
    name: ghcr
  ref:
    tag: 1.23.0
    digest: sha256:dfb436df3a0e68aa6c9536190302974db875fee1eebf7308840e2f076da9c0ea
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
