apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pangolin
  namespace: flux-system
spec:
  interval: 30m
  timeout: 15m
  releaseName: pangolin
  targetNamespace: pangolin
  dependsOn:
    - name: traefik
    - name: cert-manager
    - name: cloudnative-pg
  chart:
    spec:
      chart: pangolin
      version: 0.1.0-alpha.1
      interval: 24h
      sourceRef:
        kind: HelmRepository
        name: pangolin
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    deployment:
      type: controller
      mode: multi
      installTraefikController: false
      traefikNamespace: traefik
    images:
      pangolin:
        registry: docker.io
        repository: fosrl/pangolin
        tag: ee-postgresql-1.21.1
      gerbil:
        registry: docker.io
        repository: fosrl/gerbil
        tag: 1.4.3
      controller:
        registry: ghcr.io
        repository: fosrl/pangolin-kube-controller
        tag: 0.1.0-alpha.1
    global:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/control-plane
                    operator: DoesNotExist
    runtime:
      updateStrategy:
        type: Recreate
        rollingUpdate: null
    database:
      mode: external
      connection:
        existingSecretName: pangolin-postgresql-app
        existingSecretKey: uri
    cnpg-operator:
      enabled: false
    cnpg-cluster:
      enabled: false
    pangolin:
      replicaCount: 1
      config:
        app:
          dashboard_url: https://pangolin.kakatkarakshay.dev
          log_level: info
        domains:
          domain1:
            base_domain: kakatkarakshay.dev
            cert_resolver: letsencrypt
        gerbil:
          base_endpoint: tunnel.kakatkarakshay.dev
        traefik:
          prefer_wildcard_cert: true
        flags:
          disable_signup_without_invite: true
      ingressRoute:
        dashboard:
          enabled: true
          host: pangolin.kakatkarakshay.dev
          annotations:
            external-dns.alpha.kubernetes.io/target: gateway.kakatkarakshay.dev
          entryPoints:
            - websecure
          tls:
            enabled: true
            secretName: wildcard-kakatkarakshay-dev-tls
    controller:
      enabled: true
      replicaCount: 1
      extraEnv:
        CERTIFICATE_SECRETS: pangolin/wildcard-kakatkarakshay-dev-tls
    gerbil:
      enabled: true
      persistence:
        enabled: true
        size: 1Gi
        storageClass: longhorn
      service:
        type: ClusterIP
    networkPolicy:
      enabled: true
      gerbil:
        allowWireguardUdpEgress: true
        wireguardUdpCIDRs:
          - 0.0.0.0/0
