apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-google-oauth
  namespace: observability
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: grafana-google-oauth
    creationPolicy: Owner
  data:
    - secretKey: client-id
      remoteRef:
        key: /platform/oauth2-proxy/CLIENT_ID
    - secretKey: client-secret
      remoteRef:
        key: /platform/oauth2-proxy/CLIENT_SECRET
