apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kube-prometheus-stack-grafana
  namespace: observability
  annotations:
    helm.sh/resource-policy: keep
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  dataSourceRef:
    apiGroup: volsync.backube
    kind: ReplicationDestination
    name: grafana-restore
