apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../controllers/actions-runner-controller
  - ../controllers/longhorn
  - ../controllers/volsync
  - ../controllers/cert-manager
  - ../controllers/cloudnative-pg
  - ../controllers/metrics-server
  - ../controllers/oci-cloud-controller-manager
  - ../controllers/reloader
  - ../controllers/traefik
  - ../controllers/external-dns
  - ../controllers/oauth2-proxy
  - ../controllers/pangolin
  - infisical-kubernetes-auth.yaml
  - infisical-store.yaml
