apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: loki-storage-values
  namespace: flux-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: loki-storage-values
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        values.yaml: |
          loki:
            storage:
              s3:
                accessKeyId: {{ .accessKey | quote }}
                secretAccessKey: {{ .secretKey | quote }}
                region: {{ .region | quote }}
  data:
    - secretKey: accessKey
      remoteRef:
        key: /platform/postgres-backup/ACCESS_KEY_ID
    - secretKey: secretKey
      remoteRef:
        key: /platform/postgres-backup/ACCESS_SECRET_KEY
    - secretKey: region
      remoteRef:
        key: /platform/postgres-backup/AWS_REGION
