apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: loki-storage-values
  namespace: flux-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: loki-storage-values
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        values.yaml: |
          loki:
            storage:
              type: s3
              bucketNames:
                chunks: {{ .bucket | quote }}
                ruler: {{ .bucket | quote }}
                admin: {{ .bucket | quote }}
              s3:
                endpoint: https://{{ .endpoint }}
                accessKeyId: {{ .accessKey | quote }}
                secretAccessKey: {{ .secretKey | quote }}
                region: {{ .region | quote }}
                s3ForcePathStyle: true
  data:
    - secretKey: endpoint
      remoteRef:
        key: /platform/observability/E2_ENDPOINT
    - secretKey: bucket
      remoteRef:
        key: /platform/observability/LOKI_BUCKET
    - secretKey: accessKey
      remoteRef:
        key: /platform/postgres-backup/ACCESS_KEY_ID
    - secretKey: secretKey
      remoteRef:
        key: /platform/postgres-backup/ACCESS_SECRET_KEY
    - secretKey: region
      remoteRef:
        key: /platform/postgres-backup/AWS_REGION
