---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: authentik-cert
  namespace: authentik
spec:
  secretName: authentik-tls
  dnsNames:
    - auth.kakatkarakshay.dev
  issuerRef:
    name: cloudflare-clusterissuer
    kind: ClusterIssuer
