---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: authentik-ingress
  namespace: authentik
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`auth.kakatkarakshay.dev`)
      kind: Rule
      services:
        - name: authentik-release-server
          port: 80
  tls:
    secretName: authentik-tls
