---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: authentik
resources:
  - namespace.yaml
  - repo.yaml
  - release.yaml
  - certificate.yaml
  - ingress.yaml
configMapGenerator:
  - name: authentik-values
    files:
      - values.yaml
configurations:
  - kustomizeconfig.yaml
