---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: longhorn-cert
  namespace: longhorn-system
spec:
  secretName: longhorn-tls
  dnsNames:
    - longhorn.kakatkarakshay.dev
  issuerRef:
    name: cloudflare-clusterissuer
    kind: ClusterIssuer
