apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: traefik-oci-placement
  namespace: flux-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: traefik-oci-placement
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        values.yaml: |
          service:
            additionalServices:
              scorpion:
                annotations:
                  oci.oraclecloud.com/compartment-id: {{ .compartment | quote }}
                  oci-network-load-balancer.oraclecloud.com/subnet: {{ .subnet | quote }}
  data:
    - secretKey: compartment
      remoteRef:
        key: /platform/oci-cloud-controller-manager/tenancy-2/COMPARTMENT_ID
    - secretKey: subnet
      remoteRef:
        key: /platform/oci-cloud-controller-manager/tenancy-2/NLB_SUBNET_ID
