apiVersion: v1
kind: Secret
metadata:
  name: infisical-kubernetes-auth
  namespace: external-secrets
type: Opaque
stringData:
  identityId: 801eb111-4861-45a3-b672-0554e4bed7f8
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: infisical-external-secrets-tokenreview
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - kind: ServiceAccount
    name: external-secrets
    namespace: external-secrets
