apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../controllers/local-path-provisioner
  - ../controllers/cert-manager
  - ../controllers/cloudnative-pg
  - ../controllers/metrics-server
  - ../controllers/traefik
  - ../controllers/cloudflare
  - ../controllers/oauth2-proxy
