apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: oci-cloud-controller-manager
  namespace: kube-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: oci-cloud-controller-manager
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      data:
        cloud-provider.yaml: |
          useInstancePrincipals: true
          compartment: {{ .compartment | quote }}
          vcn: {{ .vcn | quote }}
          loadBalancer:
            subnet1: {{ .subnet | quote }}
            securityListManagementMode: None
  data:
    - secretKey: compartment
      remoteRef:
        key: /platform/oci-cloud-controller-manager/tenancy-1/COMPARTMENT_ID
    - secretKey: vcn
      remoteRef:
        key: /platform/oci-cloud-controller-manager/tenancy-1/VCN_ID
    - secretKey: subnet
      remoteRef:
        key: /platform/oci-cloud-controller-manager/tenancy-1/NLB_SUBNET_ID
