apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../controllers/local-path-provisioner
  - ../controllers/metrics-server
  - ../controllers/oci-cloud-controller-manager
  - ../controllers/reloader
  - ../cloudlab/infisical-kubernetes-auth.yaml
  - ../cloudlab/infisical-store.yaml
