apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: kubelet-serving-cert-approver
  namespace: flux-system
spec:
  interval: 24h
  ref:
    branch: main
    commit: 680cd5996b2c24f7cb576652a8b2b3ef161b8e4b
  url: https://github.com/alex1989hu/kubelet-serving-cert-approver.git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kubelet-serving-cert-approver
  namespace: flux-system
spec:
  interval: 24h
  retryInterval: 1m
  path: ./deploy/standalone
  prune: true
  wait: true
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: kubelet-serving-cert-approver
