apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flux-system
  - kubelet-serving-cert-approver.yaml
  - gateway-api.yaml
  - external-secrets.yaml
  - infrastructure.yaml
  - observability.yaml
  - apps.yaml
