apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: observability-tier1-metrics
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure-tier4-ci
  interval: 10m
  retryInterval: 1m
  path: ./observability/tier1-metrics
  prune: true
  wait: true
  timeout: 15m
  sourceRef:
    kind: GitRepository
    name: flux-system
