apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-credentials
    namespace: cloudflare
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:ts2PK/T/0Uf3Djua1GRuHXqaqkdfU3liz5ndpzC+5P6zHmQdzknVfl10Mny023e5hE3PVR8=,iv:ucSPZxlTrcSy+G+o7q+fjR4uekcIAHaFZI1cvuc5JL4=,tag:6Rw+A2TZ0pcyZXYW4vHLgQ==,type:str]
    tunnel-token: ENC[AES256_GCM,data:36dk+L3ZqSNejNebM42ofdp+pGjOXrL93CoJdWJ2p97TRB/cLNLsJuOJwK5aV3uLa2CA+5cF6eucLHVuRu1jfE6+P4EGvl6ZP/ZcrSrSLy0LlnaFLMS9xD6y2qi3ViTxLg+fI7vj8i+UMXuBgzCLYSJLm0R5DEzvlAOaYvh8Un6i7XL34UWYO+FoBHufpxxNcq2PbaaO20mu5UdjN0mhE8Huw+LLWXiknCGGx7j0OVnsvYUr5iyjHQ==,iv:JcGYVEH7oHaPrdkidQuPAMBf5jXqtcjh6c7igRw2LK4=,tag:f/H41k0MOxs/IYKOqzvd/g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvZUFiS0F2Njc0U0hXTGJw
            aHB5b0FNTzRQeWtjbXhZZUJwTlZ3OVhEVGdNCkZmQUJ1REhTaFU2dVNIdmMwcTlK
            a3JKOVpNcnlUUlluKzNqeCtCS0hNcGsKLS0tIFdWalQ2VnVlT0tqZXB2Qm9pRHNl
            ZWhxV1dMU3hjaEYxSExCSjAwSmxWS3MKE/C7fXFr4yY0drFcD9Rtm3aVZqH983yQ
            2XT+dqd/V+NhDwkaqsSUQ2H8fwy5lXXhk2fH3ru9gEHkqa9ikmMEqw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age193cn2qj237xvqtp64d8m3ztrq7s6x3d7ap6rdh9wyd563d5c9eesmgzu7w
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-21T19:11:57Z"
    mac: ENC[AES256_GCM,data:CLGoGJ0WrI7PSaGenXRUi5ToJ++rYYbyKKfXEjoIh+qj11WETzfPbh4+jNn2dfh7xHuioDXdakcp2I3kFKsvkBgqaqCLFS7PuMt+wA+3Kh+QsFPAk2qXBi9GkA3w48aRdMmrSyeTpgtxqpsvzuFwKD8mKPPFeem3KlLD7FqJpvg=,iv:TAswF2YVzhM3G4Y+qODFnUENnmvD2wOYe4OCwLb1LNc=,tag:zqoDuNRUVWh40j5SFcoLzw==,type:str]
    version: 3.13.2
