apiVersion: v1
kind: ConfigMap
metadata:
  name: authentik-blueprints
  namespace: authentik
data:
  cloudlab-forward-auth.yaml: |
    version: 1
    metadata:
      name: cloudlab-forward-auth
    entries:
      - model: authentik_providers_proxy.proxyprovider
        id: cloudlab-forward-auth
        identifiers:
          name: cloudlab-forward-auth
        attrs:
          mode: forward_domain
          external_host: https://auth.kakatkarakshay.dev
          cookie_domain: kakatkarakshay.dev
          authorization_flow:
            !Find [authentik_flows.flow, [slug, default-provider-authorization-implicit-consent]]
          invalidation_flow:
            !Find [authentik_flows.flow, [slug, default-provider-invalidation-flow]]
      - model: authentik_core.application
        identifiers:
          slug: cloudlab
        attrs:
          name: Cloudlab
          provider: !KeyOf cloudlab-forward-auth
      - model: authentik_outposts.outpost
        identifiers:
          managed: goauthentik.io/outposts/embedded
        attrs:
          providers:
            - !KeyOf cloudlab-forward-auth
          config:
            authentik_host: https://auth.kakatkarakshay.dev
            authentik_host_browser: https://auth.kakatkarakshay.dev
            authentik_host_insecure: false
            log_level: info
            object_naming_template: ak-outpost-%(name)s
            refresh_interval: minutes=5
