apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: codex-lb
  namespace: flux-system
spec:
  interval: 30m
  url: oci://ghcr.io/abyssal-labs/charts/codex-lb
  secretRef:
    name: ghcr
  ref:
    tag: latest
    digest: sha256:78b0469f1eaaa889d8af0f75bed8ee869f8295d8ffa819733e01a9b44c586bd2
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
