apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: codex-lb
  namespace: flux-system
spec:
  interval: 30m
  url: oci://ghcr.io/abyssal-labs/charts/codex-lb
  secretRef:
    name: ghcr
  ref:
    tag: latest
    digest: sha256:00f5e08f355a2ce045e2d598528030a67498867c6e7082d610239655d23373be
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
