apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: codex-lb
  namespace: flux-system
spec:
  interval: 30m
  url: oci://ghcr.io/abyssal-labs/charts/codex-lb
  secretRef:
    name: ghcr
  ref:
    tag: latest
    digest: sha256:0e7ecd4205328c90d8f13e7f39ecd650905017bfb7e8b55889226df9bff69489
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
