apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: oauth2-proxy-credentials
  namespace: oauth2-proxy
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: oauth2-proxy-credentials
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: client-id
      remoteRef:
        key: /platform/oauth2-proxy/CLIENT_ID
    - secretKey: client-secret
      remoteRef:
        key: /platform/oauth2-proxy/CLIENT_SECRET
    - secretKey: cookie-secret
      remoteRef:
        key: /platform/oauth2-proxy/COOKIE_SECRET
    - secretKey: restricted-user-access
      remoteRef:
        key: /platform/oauth2-proxy/RESTRICTED_USER_ACCESS
