apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: local-path-provisioner
  namespace: flux-system
spec:
  interval: 24h
  ref:
    tag: v0.0.37
    commit: 49b2be8e26d6d34c9afaa21fa33108d2e82f8955
  url: https://github.com/rancher/local-path-provisioner.git
