customization:
  systemExtensions:
    officialExtensions:
      - siderolabs/binfmt-misc
      - siderolabs/iscsi-tools
      - siderolabs/nfs-utils
      - siderolabs/tailscale
      - siderolabs/util-linux-tools
