apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: hourly-backup
  namespace: longhorn-system
spec:
  concurrency: 1
  cron: 0 * * * *
  groups:
    - default
  retain: 72
  task: backup
