apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager-cluster-issuer.yaml
  - longhorn-gateway.yaml
  - longhorn-recurring-job.yaml
  - longhorn-route.yaml
  - volume-snapshot-class.yaml
  - traefik-certificates.yaml
