apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: thanos-objstore
  namespace: observability
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: thanos-objstore
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        config: |
          type: S3
          config:
            bucket: {{ .bucket | quote }}
            endpoint: {{ .endpoint | quote }}
            region: {{ .region | quote }}
            access_key: {{ .accessKey | quote }}
            secret_key: {{ .secretKey | quote }}
            bucket_lookup_type: path
  data:
    - secretKey: endpoint
      remoteRef:
        key: /platform/idrive-credentials/E2_ENDPOINT
    - secretKey: bucket
      remoteRef:
        key: /platform/observability/THANOS_BUCKET
    - secretKey: accessKey
      remoteRef:
        key: /platform/idrive-credentials/ACCESS_KEY_ID
    - secretKey: secretKey
      remoteRef:
        key: /platform/idrive-credentials/ACCESS_SECRET_KEY
    - secretKey: region
      remoteRef:
        key: /platform/idrive-credentials/AWS_REGION
