apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-actions-runner
  namespace: arc-runners
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: github-actions-runner
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: github_app_id
      remoteRef:
        key: /apps/github-actions-runner/GITHUB_APP_ID
    - secretKey: github_app_installation_id
      remoteRef:
        key: /apps/github-actions-runner/GITHUB_APP_INSTALLATION_ID
    - secretKey: github_app_private_key
      remoteRef:
        key: /apps/github-actions-runner/GITHUB_APP_PRIVATE_KEY
