apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: github-actions-cache-postgresql
  namespace: github-actions-cache
spec:
  instances: 1
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - preference:
            matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: DoesNotExist
          weight: 100
  bootstrap:
    initdb:
      database: cache
      owner: cache
  storage:
    size: 5Gi
    storageClass: local-path
  resources:
    requests:
      cpu: 25m
      memory: 128Mi
