apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: github-actions-cache-server
  namespace: flux-system
spec:
  interval: 24h
  url: oci://ghcr.io/falcondev-oss/charts/github-actions-cache-server
  ref:
    tag: 1.1.3
    digest: sha256:daa902589851ac26508d391b056f92eb9630e5d47422cf937a9714688a62d339
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
