apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: headlamp
  namespace: flux-system
spec:
  interval: 30m
  releaseName: headlamp
  targetNamespace: headlamp
  chart:
    spec:
      chart: headlamp
      version: 0.44.0
      interval: 24h
      sourceRef:
        kind: HelmRepository
        name: headlamp
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    config:
      inClusterContextName: cloudlab
      oidc:
        clientID: kubernetes
        issuerURL: https://auth.kakatkarakshay.dev/application/o/kubernetes/
        scopes: profile,email
        callbackURL: https://headlamp.kakatkarakshay.dev/oidc-callback
        usePKCE: true
    clusterRoleBinding:
      create: false
    resources:
      requests:
        cpu: 25m
        memory: 64Mi
