apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: headlamp
  namespace: flux-system
spec:
  interval: 30m
  releaseName: headlamp
  targetNamespace: headlamp
  chart:
    spec:
      chart: headlamp
      version: 0.45.0
      interval: 24h
      sourceRef:
        kind: HelmRepository
        name: headlamp
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    volumes:
      - name: kubeconfig
        secret:
          secretName: headlamp-kubeconfig
    volumeMounts:
      - name: kubeconfig
        mountPath: /kubeconfig
        readOnly: true
    config:
      inClusterContextName: cloudlab
      extraArgs:
        - -kubeconfig=/kubeconfig/config
      unsafeUseServiceAccountToken: true
    clusterRoleBinding:
      create: true
      clusterRoleName: cluster-admin
    resources:
      requests:
        cpu: 25m
        memory: 64Mi
