---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana-cert
  namespace: prometheus
spec:
  secretName: grafana-tls
  dnsNames:
    - grafana.kakatkarakshay.dev
  issuerRef:
    name: cloudflare-clusterissuer
    kind: ClusterIssuer
