apiVersion: v1
kind: Secret
metadata:
    name: oauth2-proxy-credentials
    namespace: oauth2-proxy
type: Opaque
stringData:
    client-id: ENC[AES256_GCM,data:FZgTXiIoMuHjoYgBY7iPMNdDgXD5FUKQ8tWh6nNHAgx31Gnr81+HMBDRUH7PmL4oklLeOir4iV2EzPSEsi/4HP+9c9eC/VRG,iv:ax++kN/mRHdKcjOvvPXCBPs/0G90TL1kDDvjO8j/Rzk=,tag:wp2zjWqIcn5ayBgLcailNQ==,type:str]
    client-secret: ENC[AES256_GCM,data:AisJezVSLTRYGXjZdhGb4rz8GEUcI08B0TjnxoNVySl9HUk=,iv:6D05UhgvuE1xdOluA7mlHtx/0GjIo4nn/O2EceXYcAo=,tag:i6/GqdagsFzDT+QjcJkYiQ==,type:str]
    cookie-secret: ENC[AES256_GCM,data:8IlmANaeraqkKvE1QTWwXU9cTWOef5/34sWR25BuxyJ8WTaDJ2ytZkAgios=,iv:WhECWKvw3c3gWGBd3nawlKm5G2m9ohzURTSUbhzcggg=,tag:GlH4KLpAyv0vO20Eh46LJg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmWm5hUE5TU1owRzdGRU5r
            cGxKZktCS0p4dnZyUmpIY0ZMdHNXRjdMT0UwCkhnalJkbC9DRXc4RUhtZWhqb0Vt
            Vmd5ZVVaa21mYmxtNzl4VXNtaDFta2sKLS0tIDVBaDJQenlvZnA5MnRBZlF3eEM3
            VUlpRzJCNUhQdldoMnNLcUI3T1h6VVkKfw3PkJ5SgtVgK5nWVrKtdhrTAxGPKv5T
            4gFA7XMooyvWYAbrVMVKOnktshpJLuxh8BOSfVq6H6NeDMvUhHkOrQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age193cn2qj237xvqtp64d8m3ztrq7s6x3d7ap6rdh9wyd563d5c9eesmgzu7w
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-21T19:19:50Z"
    mac: ENC[AES256_GCM,data:1Ii31YCAsuO2/ZusjmRhvIqJybCtofFbmBacgbz2boAbg+W3E6TCGprgHANoyw4esYrJX2jcq4thc1v/X7JY5XWMHZ+CBin8nsQ1Ws1+vzG2g/u+8UftHEM1j4Cdk45Tb5zGRgJS9FTU/8DiefpjEjB9glcFpko/WU7lnGD3M7s=,iv:tpIWmOIHr0hvg6uptml48cYn1Sklk/+iJnZWvFc9VPE=,tag:r/gmL4MdgQ8nwEkzPjfiXQ==,type:str]
    version: 3.13.2
