apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: idrive-e2-credentials
  namespace: postgresql
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: idrive-e2-credentials
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: ACCESS_KEY_ID
      remoteRef:
        key: /platform/idrive-credentials/ACCESS_KEY_ID
    - secretKey: ACCESS_SECRET_KEY
      remoteRef:
        key: /platform/idrive-credentials/ACCESS_SECRET_KEY
    - secretKey: AWS_REGION
      remoteRef:
        key: /platform/idrive-credentials/AWS_REGION
